# Generated by Django 5.1.6 on 2025-04-02 04:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptNotes', '0002_alter_post_id_note_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
