# Generated by Django 5.1.6 on 2025-04-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptNotes', '0003_alter_note_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
