# Generated by Django 5.1.6 on 2025-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptNotes', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
