# Generated by Django 5.1.6 on 2025-05-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptNotes', '0005_note_categorized_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
